### ISSUE TITLE
Add an example

### ISSUE THREAD

**Issue by DrPsychick** [DrPsychick/docker-texlive-guitartex#1]
* Any random song out there
* Generate PDF and add it to repo as an example (with the source)
* Run it during pipeline to validate functionality

**Comment by debjit20504** [comment]
Could you please elaborate what's the issue?

**Comment by DrPsychick** [comment]
Sure. I'd like to have an example gtx file to the in the repo as well as the resulting PDF to show people what this is good for.

Additionally, with an example it is possible to verify in the pipeline that it still works after making changes (generates a PDF).

`g[E]imme all your lovin' and be n[D]ice to me`

in the `song.gtx` would be printed in pdf like so: 
<img width="375" alt="image" src="https://user-images.githubusercontent.com/18177732/183259120-445a2b09-0c7d-4087-a00f-a14f9ae23f16.png">
